arx-deidentifier/arx

data/test_dirty.csv
src/example/org/deidentifier/arx/examples/Example14.java
src/example/org/deidentifier/arx/examples/Example28.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/HierarchyWizard.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/HierarchyWizardModel.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/HierarchyWizardModelGrouping.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/HierarchyWizardPageType.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/ImportWizard.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/ImportWizardModel.java
src/gui/org/deidentifier/arx/gui/view/impl/wizard/ImportWizardPageColumns.java
src/main/org/deidentifier/arx/Data.java
src/main/org/deidentifier/arx/DataHandle.java
src/main/org/deidentifier/arx/DataSource.java
src/main/org/deidentifier/arx/DataType.java
src/main/org/deidentifier/arx/aggregates/HierarchyBuilderIntervalBased.java
src/main/org/deidentifier/arx/io/CSVDataInput.java
src/main/org/deidentifier/arx/io/ImportAdapterCSV.java
src/main/org/deidentifier/arx/io/ImportAdapterExcel.java
src/main/org/deidentifier/arx/io/ImportAdapterJDBC.java
src/main/org/deidentifier/arx/io/ImportColumn.java
src/main/org/deidentifier/arx/io/ImportColumnCSV.java
src/main/org/deidentifier/arx/io/ImportColumnExcel.java
src/main/org/deidentifier/arx/io/ImportColumnIndexed.java
src/main/org/deidentifier/arx/io/ImportColumnJDBC.java
src/main/org/deidentifier/arx/metric/v2/DomainShareInterval.java

Merge cleansing functionalities into master

Merge cleansing functionalities into master

---

src/gui/org/deidentifier/arx/gui/worker/WorkerLoad.java
src/gui/org/deidentifier/arx/gui/worker/WorkerSave.java

Fix: Add null-checks when writing/loading project.

Bug: NPE when saving project without data.

---

src/gui/org/deidentifier/arx/gui/view/impl/utility/ViewStatisticsLogisticRegression.java

- F-Score was missing from tooltip
- Recall showed wrong data

Bugfix: Tooltip for precision, recall, f-score.

---

src/gui/org/deidentifier/arx/gui/view/impl/define/ViewAttributeList.java

- show context menu if right click on columns Data type or Format
- toggle response variable if left click on colum Response variables

Fix mouseevent action in Attribute metadata

---

src/gui/org/deidentifier/arx/gui/view/impl/define/ViewAttributeTransformation.java

When changing all attribute types at once via GUI the currently selected attribute's type has to be changed in the combo box.

Update attribute type of selected attribute in GUI.

---

src/main/org/deidentifier/arx/aggregates/ClassificationConfigurationLogisticRegression.java

Use default values from the master branch.

Bugfix: Default values of logistic regression classifier.

---

src/main/org/deidentifier/arx/reliability/IntervalArithmeticDouble.java

Add comments which justify the method used for calculating lower and

---

src/gui/org/deidentifier/arx/gui/Controller.java
src/gui/org/deidentifier/arx/gui/model/Model.java
src/gui/org/deidentifier/arx/gui/view/impl/utility/ViewStatisticsClassificationAttributes.java
src/main/org/deidentifier/arx/aggregates/StatisticsClassification.java
src/main/org/deidentifier/arx/aggregates/classification/MultiClassNaiveBayes.java

Update target variables (image) after response variables have changed.
* Add response variables to the State
* Add listener/update for ModelPart.RESPONSE_VARIABLES
* Choose target image based on type and whether isResponseVariable
Set classification parameter after anonymization process is completed.
* Set all quasi-identifying attributes as feature variables
* Set all response variables, if any, as target variables
And minor changes.

Classification changes

---

src/gui/org/deidentifier/arx/gui/model/Model.java
src/gui/org/deidentifier/arx/gui/model/ModelR.java
src/gui/org/deidentifier/arx/gui/view/impl/menu/DialogProperties.java
src/gui/org/deidentifier/arx/gui/view/impl/utility/AnalysisContextR.java
src/gui/org/deidentifier/arx/gui/view/impl/utility/LayoutUtilityStatistics.java
src/gui/org/deidentifier/arx/gui/view/impl/utility/ViewStatisticsRTerminal.java
src/gui/org/deidentifier/arx/r/RBuffer.java

Integration of R Terminal into Utility Analysis. Added R settings to ARX settings. Initialization of input and output table in R with the data from within ARX.

R terminal integration

---

src/test/org/deidentifier/arx/test/TestClassification.java

* Fix logistic regression JUnit-Tests for Brier score and AUC
* Fix naive bayes JUnit-Tests for AUC
* Add naive bayes JUnit-Tests for sensitivity, specificity and brier score

Fix LR Junit-Tests. Extend NB Junit-Tests.

---

src/test/org/deidentifier/arx/test/TestAnonymizationCellSuppression.java

reorder risk measures in output and in method parameters to be constistent

---

src/gui/org/deidentifier/arx/gui/worker/WorkerSave.java

Try saving project to temporary file and only if successful save to
actual target file.

Handle: Saving projects with errors.

---

src/main/org/deidentifier/arx/aggregates/StatisticsBuilderInterruptible.java
src/main/org/deidentifier/arx/aggregates/classification/MultiClassRandomForest.java

* Bugfix: handle sparse class values
* Update comment
* Bugfix: handle errors correctly

Rf fixes (#179)

---

src/main/org/deidentifier/arx/aggregates/StatisticsClassification.java

Implement multinomial brier score and brier skill score.

Implement multinomial Brier score (#165)

---

src/gui/org/deidentifier/arx/gui/resources/messages.properties
src/gui/org/deidentifier/arx/gui/view/impl/utility/ViewStatisticsClassificationOutput.java

Extend GUI to show the Brier skill score in the performance overview table of the output.

Add Brier skill score to performance overview table (output).

---

src/example/org/deidentifier/arx/examples/Example59.java
src/main/org/deidentifier/arx/AttributeType.java
src/main/org/deidentifier/arx/masking/DataMaskingFunction.java

I implemented the first release of Fisher-Yates Knuth-Yao permutation algorithm and create a example file to test the permutation.

First implementation of the Fisher-Yates Knuth-Yao permutation algorithm on column

---

src/example/org/deidentifier/arx/examples/Example59.java
src/main/org/deidentifier/arx/AttributeType.java
src/main/org/deidentifier/arx/masking/DataMaskingFunction.java

this is only the first implementation, I will work to improve the code further.

 First implementation of the Rao-Sandelius permutation algorithm on column

---

src/main/org/deidentifier/arx/framework/data/Dictionary.java
src/main/org/deidentifier/arx/framework/data/GeneralizationHierarchy.java

Make error message more verbose

---

pom.xml

Added a maven build profile that will package the code without any GUI components.

Maven core

---

readme.md

Sorry about the delay, I was out for the weekend.
How does this sound for a note about building the core code?

added note for building core code

---

src/main/org/deidentifier/arx/aggregates/HierarchyBuilderDate.java

Fix Arx [issue 366](https://github.com/arx-deidentifier/arx/issues/366).

Fix a bug in date hierarchy month/year

---

src/gui/org/deidentifier/arx/gui/resources/messages.properties
src/gui/org/deidentifier/arx/gui/view/impl/common/ComponentGSSlider.java

Show the generalization and suppression factor value!

view coding model slider value
